[build]
  base = "frontend"
  command = "npm install --unsafe-perm --no-audit --no-fund && chmod +x node_modules/.bin/react-scripts && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "@react_app_api_url"
